bookmark/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [

    path('admin/', admin.site.urls),
    path('account/', include('registration.urls')),
    path('search_view/', include('search_book.urls', namespace='search')),
    path('', include('books.urls', namespace='book')),


]

if settings.DEBUG:
    urlpatterns+=static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

books/urls.py
from django.urls import path
from . import views
from .forms import CommentForm
from .models import Comment,Book
from django.http import request
from .views import BookDetailView,CommentView

app_name = 'books'

urlpatterns = [
    path('',views.BookListView.as_view(), name='book_list'),
    path('<slug:slug>/', views.BookDetailView.as_view(), name='book_detail'),
    path('<int:pk>/comment',views.CommentView.as_view(), name='book_comments'),
    path('<int:pk>/comments', views.CommentView.comment_delete, name='delete'),
    path('<int:pk>/comment_edit', views.CommentUpdate.as_view(),name='edit'),

]

registration/urls.py
from django.urls import path,include
from .views import RegistrationView
from . import views



urlpatterns=[

    path('', include('django.contrib.auth.urls')),
    path('', views.dashboard, name='dashboard'),
    path('register/',RegistrationView.as_view() , name='register'),
]

search_book/urls.py
from django.urls import path
from . import views
from .views import TestView,SearchResultsView


app_name = 'search_book'

urlpatterns = [
    path('',views.TestView.as_view(), name='test_view'),
    path('/search',views.SearchResultsView.as_view(), name="search_result")

]



books/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse



class Book(models.Model):

    title = models.CharField(max_length=200)
    author = models.CharField(max_length=100)
    slug = models.SlugField(max_length=250,
                           unique_for_date='created')
    image = models.ImageField(upload_to='images/%Y/%m/%d/')
    description = models.TextField(blank=True)
    created = models.DateField(auto_now=True)

    class Meta:
        indexes = [
            models.Index(fields=['id','-title']),
        ]
        ordering = ['-title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('books:book_detail',
                       args=[
                            self.slug]
                       )

class Comment(models.Model):
    book = models.ForeignKey(Book,
                             on_delete=models.CASCADE,
                             related_name='book_comments')
    username = models.ForeignKey(User,
                                 on_delete=models.CASCADE,
                                 related_name='user_comments')
    created=models.DateField(auto_now_add=True)
    body_description = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['id','created'])
        ]

    def __str__(self):
        return f'Комментирует {self.username} на {self.book}'

    def get_absolute_url(self):
        return reverse('book:book_detail', args=[str(self.book.slug)])

search_book/models.py
from django.db import models

# Create your models here.

books/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=['id','body_description',]


books/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, View, UpdateView, TemplateView
from django.views.generic.edit import FormMixin
from .models import Book, Comment
from .forms import CommentForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.db.models import Q


class BookListView(ListView):
    queryset = Book.objects.all()
    context_object_name = 'books'
    template_name = 'books/book_list.html'


class BookDetailView(DetailView):
    model = Book
    context_object_name = 'book'
    template_name = 'books/book_detail.html'
    book = model.objects.all()

    def get_context_data(self, **kwargs):
        comments = self.book.filter(book_comments__active=True)
        context = super().get_context_data(**kwargs)
        context['comments'] = comments
        context['form'] = CommentForm()
        return context


class CommentView(LoginRequiredMixin, View):
    model = Comment
    context_object_name = 'comments'
    form_class = CommentForm
    template_name = 'books/comment.html'
    login_url = 'login'
    redirect_field_name = 'redirect to'

    def get(self, request, pk, book_pk, *args, **kwargs):
        form = self.form_class
        book = get_object_or_404(Book, id=book_pk)
        comment = get_object_or_404(Comment, pk=pk)
        return render(request, 'books/includes/edit_comment.html', {'book': book, 'comment': comment, 'form': form})

    def post(self, request, pk, *args, **kwargs):
        form = CommentForm(data=request.POST)
        comment = None
        book = get_object_or_404(Book, id=pk)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.book = book
            comment.username = request.user
            comment.save()
        return render(request, self.template_name, {'book': book, 'form': form, 'comment': comment})

    def comment_delete(self, pk):
        comment = get_object_or_404(Comment, pk=pk)
        comment.delete()
        return redirect('dashboard')


class CommentUpdate(LoginRequiredMixin, UpdateView):
    model = Comment
    form_class = CommentForm
    template_name = 'books/includes/edit_comment.html'
    login_url = 'login'
    redirect_field_name = 'redirect to'



search_book/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView
from books.models import Book
from django.db.models import Q

# Create your views here.
class TestView(TemplateView):
    template_name = 'search/search_view.html'
    context_object_name = 'test'

class SearchResultsView(ListView):
    model = Book
    template_name = 'search/search_result.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list= Book.objects.filter(
            Q(title__icontains=query) | Q(author__icontains=query)
        )
        return object_list

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
</head>
<body>
<div id="header">
    <span class="logo">Bookmarks</span>
    <ul class="menu">
        <li {% if section == "dashboard" %}class="selected"{% endif %}>
            <a href="{% url "dashboard" %}">Bookboard</a>
             <a href="{% url "search:test_view" %}">Search</a>
    </ul>
    <span class="user">
 {% if request.user.is_authenticated %}
     Hello world! {{ request.user.first_name|default:request.user.username }},
     <a href="{% url "logout" %}">Выход</a>
 {% else %}
     <a href="{% url "login" %}">Вход</a>
 {% endif %}
 </span>
    <div id="content">
        {% block content %}
            <a href="{book.get_absolute_url}">{{ book.title }}</a>
        {% endblock %}
    </div>
</div>
</body>
</html>

templates/books/book_detail.html
{% extends "base.html" %}

{% block title %} {{ book.title }} {% endblock %}

{% block content %}
    <h1>{{ book.title }}</h1>
    <img src="{{ book.image.url }}" , width="100" , height="150">
    <p class="date">Published at {{ book.created }}</p>
    <p>Автор-{{ book.author }}</p>
    {{ book.description|linebreaks }}
    {% for comment in book.book_comments.all %}
        <div class="comment">
            <p class="info">
                Комментарий {{ forloop.counter }} оставлен {{ comment.username }}
                {{ comment.created }}
            </p>
            {{ comment.body_description|linebreaks }}
            {% if user.id == comment.username.id %}
                <a href="{% url 'book:edit' comment.pk  %}" methods="post"><span class="glyphicon glyphicon-pencil">Edit</span></a>
                <a href="{% url 'book:delete' comment.pk %}">Delete</a>

            {% endif %}
        </div>
    {% empty %}
        <p>Пока что никто не оставил комментариев</p>
    {% endfor %}
    {% include "books/includes/comment_form.html" %}
{% endblock %}

templates/books/book_list.html
{% extends "base.html" %}

{% block title %}BooksForMarks{% endblock %}
{% block content %}
    <h1>BookS</h1>
    {%  for book in books%}
    <h2>
            <a href="{{book.get_absolute_url}}">
                {{ book.title }}
            </a>
    </h2>
        <img src="{{ book.image.url }}", width="100", height="150">
    <p class="date">
    Written by {{ book.author }}
    </p>
    {{ book.description|truncatewords:30|linebreaks }}
    {% endfor %}
{% endblock %}

templates/books/comment.html
{% extends "base.html" %}
{% block title %}Добавление комментария{% endblock %}
{% block content %}
 {% if comment %}
 <h2>Ваш комментарий добавлен.</h2>
 <p><a href="{{ book.get_absolute_url }}">Назад к посту</a></p>
 {% else %}
 {% include "books/includes/comment_form.html" %}
 {% endif %}
{% endblock %}

templates/books/includes/comment_form.html
<h2>Добавить новый комментарий</h2>
<form action="{% url 'book:book_comments' book.id %}" method="post">
    {{ form }}
 {% csrf_token %}
 <p><input type="submit" value="Добавить комментарий"></p>
</form>

templates/books/includes/edit_comment.html
{% extends "base.html" %}
{% block title %}Измените комментарий{% endblock %}
{% block content %}
    <form action="{% url 'book:edit' comment.pk %}" method="post">
        {{ form }}
        {% csrf_token %}
        <p><input type="submit" value="Добавить комментарий"></p>
    </form>
{% endblock %}

templates/search/search_result.html
{% extends "base.html" %}
{% block title %}Search Results{% endblock %}
{% block content %}
<h1>Search Results</h1>

    <ul>
        {% for book in object_list %}
            <li>
               {{ book.title }} {{ book.author }}
            </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/search/search_view.html
{% extends "base.html" %}
{% block title %}Поиск книг{% endblock %}
{% block content %}
    <h1>Введите для название книги или автора для поиска</h1>
    <form action="{% url 'search:search_result' %}" method="get">
        <input name="q" type="text" placeholder="Search...">
    </form>
{% endblock %}
